steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}
  - --cache=true
  - --cache-ttl=1h

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - dataflow
  - flex-template
  - build
  - ${_TEMPLATE_PATH}
  - --image=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}
  - --sdk-language="PYTHON"
  - --metadata-file="./metadata.json"
